### ISSUE TITLE
Faut finir ça mon gars

### ISSUE THREAD

**Issue by Tomy216** [UPS-ILU/ILU2-POO-TP2#1]
![image](https://github.com/UPS-ILU/ILU2-POO-TP2/assets/123976896/aed8f0af-490e-4447-a549-bd27d67ea21d)
![image](https://github.com/UPS-ILU/ILU2-POO-TP2/assets/123976896/2cd88e95-4dd1-42f0-8008-45fbdc3d0925)

**Comment by haissammsa** [comment]
Thank you for reporting this issue we will treat is as soon as possible.
